### ISSUE TITLE
FTP command is not generated into preseed

### ISSUE THREAD

**Issue by xeluior** [xeluior/genisys#83]
With this config:
```yaml
---
Network:
  interface: enp0s8
  subnet: 10.0.0.0/24
  ip: 10.0.0.1
  dhcp-ranges: 10.0.0.100,10.0.0.200
  dhcp-lease: 12h
  no-dhcp: false
  nat-requests: true
  nat-interface: enp0s3
  tftp_directory: /var/tftp
  tftp_port: 69
  dns-servers: 10.0.2.3
  no-dns: false
  ftp:
    directory: /var/ftp
    ftp-port: 21
  server:
    port: 15206
    user: genisys
    group: genisys
    working-directory: /srv/genisys
    ssl:
OS:
  os: debian
  version-name: bookworm
  target-architecture: amd64 
UEFI:
  uefi: false
Users:
  root-login: true
  root-password: $y$j9T$k9pvIgLcX46WAFwiGuhBx0$r4v90dAT1d0msSAtLP1e.LZ7qNpyYQ4OYa9VCvZeLcD # "password"
  username: alice
  password: $y$j9T$k9pvIgLcX46WAFwiGuhBx0$r4v90dAT1d0msSAtLP1e.LZ7qNpyYQ4OYa9VCvZeLcD
  ssh-keys:
    - /app/ssh/id_rs.pub
  sudoer: true
Applications:
  - curl
```
We expect
```
# preseed.cfg
...
d-i preseed/late-command string wget -nd -m ftp://10.0.0.1:21/first-boot -P /first-boot
...
```
But the line is absent.
